/**
 * Blocklist validation data: valid TLDs and known desktop app names.
 * Ported from desktop app (gui/app.py). Used by validators.js for URL/app validation.
 */

export const VALID_TLDS = new Set([
  "ai",
  "app",
  "ar",
  "at",
  "au",
  "be",
  "biz",
  "blog",
  "br",
  "ca",
  "ch",
  "cl",
  "cloud",
  "cn",
  "co",
  "co.in",
  "co.jp",
  "co.nz",
  "co.uk",
  "com",
  "com.au",
  "com.br",
  "cz",
  "de",
  "dev",
  "dk",
  "edu",
  "es",
  "fi",
  "fr",
  "gg",
  "gov",
  "hk",
  "ie",
  "in",
  "info",
  "int",
  "io",
  "it",
  "jp",
  "kr",
  "me",
  "mil",
  "mx",
  "net",
  "nl",
  "no",
  "nz",
  "online",
  "org",
  "pl",
  "pro",
  "ru",
  "se",
  "sg",
  "shop",
  "site",
  "store",
  "tech",
  "tv",
  "tw",
  "uk",
  "us",
  "xyz",
  "za"
]);

export const KNOWN_APPS = new Set([
  ",\n        ",
  ",\n        # B\n        ",
  ",\n        # C\n        ",
  ",\n        # D\n        ",
  ",\n        # E\n        ",
  ",\n        # F\n        ",
  ",\n        # G\n        ",
  ",\n        # H\n        ",
  ",\n        # I\n        ",
  ",\n        # J\n        ",
  ",\n        # K\n        ",
  ",\n        # L\n        ",
  ",\n        # M\n        ",
  ",\n        # N\n        ",
  ", ",
  "1password",
  "3ds max",
  "7-zip",
  "7zip",
  "ableton",
  "ableton live",
  "abstract",
  "access",
  "acdsee",
  "acoustica",
  "acrobat",
  "acrobat reader",
  "activity monitor",
  "address book",
  "adminer",
  "adobe acrobat",
  "adobe after effects",
  "adobe animate",
  "adobe audition",
  "adobe bridge",
  "adobe creative cloud",
  "adobe dimension",
  "adobe dreamweaver",
  "adobe fresco",
  "adobe illustrator",
  "adobe indesign",
  "adobe lightroom",
  "adobe media encoder",
  "adobe photoshop",
  "adobe premiere",
  "adobe reader",
  "adobe xd",
  "affinity designer",
  "affinity photo",
  "affinity publisher",
  "after effects",
  "age of empires",
  "age of empires ii",
  "age of empires iii",
  "age of empires iv",
  "airbnb",
  "airtable",
  "alacritty",
  "alan wake",
  "alan wake 2",
  "alexa",
  "alfred",
  "alien isolation",
  "amadeus pro",
  "amarok",
  "amazon games",
  "amazon kindle",
  "amazon luna",
  "amazon music",
  "amazon photos",
  "amazon prime video",
  "amd relive",
  "amnesia",
  "among us",
  "amphetamine",
  "anchor",
  "android emulator",
  "android studio",
  "animal crossing",
  "animate",
  "anki",
  "anno 1800",
  "ansible",
  "anthem",
  "any.do",
  "anytype",
  "apex legends",
  "app cleaner",
  "app store",
  "app zapper",
  "appcleaner",
  "apple books",
  "apple health",
  "apple home",
  "apple maps",
  "apple music",
  "apple news",
  "apple notes",
  "apple podcasts",
  "apple tv",
  "apple tv+",
  "apptrap",
  "arc",
  "arc browser",
  "archiver",
  "ardour",
  "ark survival ascended",
  "ark survival evolved",
  "arma 3",
  "armored core vi",
  "artrage",
  "asana",
  "aseprite",
  "assassin\\",
  "assassins creed",
  "atom",
  "audacity",
  "audiomack",
  "audition",
  "aura",
  "autocad",
  "autodesk 3ds max",
  "autodesk maya",
  "autosleep",
  "avast",
  "avg",
  "avid",
  "avid media composer",
  "avid pro tools",
  "azure data studio",
  "azure devops",
  "babbel",
  "balance",
  "baldur\\",
  "baldurs gate 3",
  "bandcamp",
  "bandizip",
  "bandlab",
  "bartender",
  "basecamp",
  "battle.net",
  "bbedit",
  "bear",
  "bethesda launcher",
  "bethesda.net launcher",
  "bettertouchtool",
  "betterzip",
  "bilibili",
  "binance",
  "bitbucket",
  "bitdefender",
  "bitwarden",
  "bitwig",
  "bitwig studio",
  "bleachbit",
  "blender",
  "blizzard",
  "blizzard battle.net",
  "bloomberg",
  "bluejeans",
  "bluesky",
  "bluestacks",
  "bodymovin",
  "booking",
  "books",
  "bootcamp",
  "botw",
  "box",
  "box drive",
  "brackets",
  "brainscape",
  "brave",
  "brave browser",
  "breath of the wild",
  "bridge",
  "brilliant",
  "browserstack",
  "buffer",
  "busuu",
  "busycal",
  "byword",
  "c4d",
  "caffeine",
  "calca",
  "calculator",
  "calendar",
  "calendly",
  "calibre",
  "calligra",
  "calm",
  "camtasia",
  "canva",
  "capacities",
  "capture one",
  "carbon copy cloner",
  "cardhop",
  "carrot weather",
  "castro",
  "cavalry",
  "ccleaner",
  "cemu",
  "chanty",
  "character animator",
  "charles",
  "charles proxy",
  "cheatsheet",
  "chromatic",
  "chrome",
  "chromium",
  "chronosync",
  "cinema 4d",
  "circleci",
  "cisco webex",
  "citavi",
  "citra",
  "cleanmymac",
  "cleanmymac x",
  "cleanshot",
  "cleanshot x",
  "clementine",
  "clickup",
  "clion",
  "clip studio",
  "clip studio paint",
  "clipboard manager",
  "clipchamp",
  "clock",
  "clockify",
  "clubhouse",
  "cmd",
  "cmder",
  "cocos",
  "coda",
  "code",
  "code blocks",
  "codeblocks",
  "codecademy",
  "coinbase",
  "command prompt",
  "commander one",
  "compass",
  "construct",
  "contacts",
  "contexts",
  "control panel",
  "copied",
  "copy clip",
  "corel painter",
  "coreldraw",
  "coursera",
  "craft",
  "creative cloud",
  "crossover",
  "crunchyroll",
  "cubase",
  "cursor",
  "cyberduck",
  "cyberghost",
  "dailymotion",
  "dark sky",
  "darkroom",
  "darktable",
  "dashlane",
  "data rescue",
  "datacamp",
  "datagrip",
  "davinci",
  "davinci resolve",
  "db browser",
  "dbeaver",
  "deepl",
  "deezer",
  "defold",
  "descript",
  "desktime",
  "desmos",
  "desmume",
  "dictionary",
  "digikam",
  "dimension",
  "directory opus",
  "discord",
  "disk drill",
  "disk utility",
  "disney plus",
  "disney+",
  "ditto",
  "division 2",
  "divvy",
  "docker",
  "docker desktop",
  "dolphin",
  "domestika",
  "doom emacs",
  "doordash",
  "doppler",
  "dosbox",
  "double commander",
  "dozer",
  "dreamweaver",
  "dropbox",
  "droplr",
  "duckduckgo",
  "duckduckgo browser",
  "duolingo",
  "dynalist",
  "ea app",
  "ea desktop",
  "ea play",
  "eclipse",
  "edge",
  "edx",
  "elder scrolls",
  "elder scrolls online",
  "element",
  "elmedia",
  "emacs",
  "emby",
  "endnote",
  "enpass",
  "enscape",
  "epic games",
  "epic games launcher",
  "epicgameslauncher",
  "epsxe",
  "eset",
  "eso",
  "everhour",
  "evernote",
  "excel",
  "expedia",
  "explorer",
  "expressvpn",
  "facebook",
  "facebook messenger",
  "facetime",
  "fantastical",
  "fastic",
  "feedly",
  "ferrite",
  "fiddler",
  "figjam",
  "figma",
  "file explorer",
  "filezilla",
  "filmora",
  "final cut",
  "final cut pro",
  "final draft",
  "finder",
  "fire alpaca",
  "fire emblem",
  "firefox",
  "fission",
  "fitbit",
  "fl studio",
  "flashcards",
  "fleet",
  "flickr",
  "flipboard",
  "flock",
  "floorp",
  "flycut",
  "foobar2000",
  "fork",
  "forklift",
  "foxit reader",
  "freeoffice",
  "fresco",
  "freshbooks",
  "fruity loops",
  "funimation",
  "fusion 360",
  "game maker studio",
  "gamemaker",
  "garageband",
  "garmin connect",
  "geforce experience",
  "geforce now",
  "geogebra",
  "gif brewery",
  "gimp",
  "giphy capture",
  "git",
  "git bash",
  "git gui",
  "gitea",
  "github",
  "github actions",
  "github desktop",
  "gitkraken",
  "gitlab",
  "gitx",
  "godot",
  "godot engine",
  "gog",
  "gog galaxy",
  "gog galaxy 2.0",
  "gogs",
  "goland",
  "gom player",
  "goodnotes",
  "google",
  "google calendar",
  "google chat",
  "google chrome",
  "google docs",
  "google drive",
  "google forms",
  "google home",
  "google keep",
  "google maps",
  "google meet",
  "google news",
  "google photos",
  "google play books",
  "google podcasts",
  "google sheets",
  "google sites",
  "google slides",
  "google translate",
  "goto meeting",
  "gotomeeting",
  "grammarly",
  "graphics gale",
  "gravit designer",
  "greenshot",
  "grubhub",
  "habit tracker",
  "habitica",
  "habitify",
  "harvest",
  "hazel",
  "hbo max",
  "headspace",
  "health",
  "heidisql",
  "height",
  "helix",
  "hemingway",
  "heptabase",
  "hidden bar",
  "hidive",
  "hitfilm",
  "home",
  "homekit",
  "hootsuite",
  "hoppscotch",
  "hotspot shield",
  "houdini",
  "htop",
  "httpie",
  "hubspot",
  "hulu",
  "humble app",
  "humble bundle",
  "hyper",
  "ia writer",
  "icloud",
  "icloud drive",
  "iina",
  "illustrator",
  "imessage",
  "imovie",
  "indesign",
  "infuse",
  "inkscape",
  "inoreader",
  "insight timer",
  "insomnia",
  "instagram",
  "instapaper",
  "intellij",
  "intellij idea",
  "invision",
  "ios simulator",
  "ipvanish",
  "isaac",
  "istat menus",
  "itch",
  "itch.io",
  "iterm",
  "iterm2",
  "itunes",
  "ivpn",
  "izotope rx",
  "jellyfin",
  "jenkins",
  "jira",
  "joplin",
  "just press record",
  "k9s",
  "kakaotalk",
  "kap",
  "kapwing",
  "karabiner",
  "kaspersky",
  "kdenlive",
  "keepass",
  "keepassxc",
  "keeper",
  "keka",
  "keyboard maestro",
  "keynote",
  "keyshot",
  "khan academy",
  "kick",
  "kindle",
  "kirby",
  "kitty",
  "kmplayer",
  "kobo",
  "kodi",
  "kraken",
  "krita",
  "kubectl",
  "kubernetes",
  "languagetool",
  "lapce",
  "lastpass",
  "later",
  "launchbar",
  "launchbox",
  "ldplayer",
  "lens",
  "level",
  "libreoffice",
  "libreoffice base",
  "libreoffice calc",
  "libreoffice draw",
  "libreoffice impress",
  "libreoffice writer",
  "librewolf",
  "licecap",
  "life fasting",
  "lifesum",
  "lightroom",
  "lightroom classic",
  "lightshot",
  "lightstream",
  "lightwave",
  "lightworks",
  "like a dragon",
  "line",
  "linear",
  "linearity curve",
  "linguee",
  "linkedin",
  "linkedin learning",
  "little snitch",
  "lmms",
  "localtunnel",
  "logic",
  "logic pro",
  "logic pro x",
  "logseq",
  "loom",
  "lose it",
  "lottie",
  "lucidchart",
  "luigi mansion",
  "lulu",
  "luminar",
  "lumion",
  "lunacy",
  "lungo",
  "lyft",
  "mac app store",
  "maccy",
  "magix vegas",
  "magnet",
  "magnifier",
  "mail",
  "malwarebytes",
  "mame",
  "mapmyrun",
  "maps",
  "mario",
  "mario kart",
  "mario odyssey",
  "marvelous designer",
  "masterclass",
  "mastodon",
  "mathematica",
  "matlab",
  "matrix",
  "matter",
  "mattermost",
  "max",
  "maxthon",
  "maya",
  "mcafee",
  "measure",
  "media encoder",
  "medibang",
  "medium",
  "mega",
  "melonds",
  "mem",
  "memrise",
  "memu",
  "mendeley",
  "menumeters",
  "messages",
  "messenger",
  "metatrader",
  "metroid",
  "metroid dread",
  "mgba",
  "microsoft 365",
  "microsoft access",
  "microsoft edge",
  "microsoft excel",
  "microsoft onedrive",
  "microsoft onenote",
  "microsoft outlook",
  "microsoft powerpoint",
  "microsoft project",
  "microsoft publisher",
  "microsoft store",
  "microsoft teams",
  "microsoft to do",
  "microsoft visio",
  "microsoft word",
  "mindmeister",
  "mindnode",
  "minikube",
  "mint",
  "miro",
  "mixcraft",
  "moba xterm",
  "mobaxterm",
  "modo",
  "monday",
  "monday.com",
  "mongodb compass",
  "monitorcontrol",
  "monosnap",
  "moom",
  "moonlight",
  "movavi",
  "movist",
  "mozilla firefox",
  "mpc-hc",
  "mplayerx",
  "mpv",
  "mudbox",
  "mullvad",
  "mural",
  "music",
  "musicbee",
  "myfitnesspal",
  "myki",
  "mypaint",
  "mysql workbench",
  "nano",
  "nanoleaf",
  "navicat",
  "neovim",
  "nest",
  "netbeans",
  "netflix",
  "netnewswire",
  "news",
  "nextcloud",
  "ngrok",
  "nike run club",
  "nintendo switch",
  "nitro pdf",
  "nook",
  "noom",
  "nordpass",
  "nordvpn",
  "norton",
  "notability",
  "notepad++",
  "notes",
  "notion",
  "notion calendar",
  "nova",
  "noxplayer",
  "nuendo",
  "numbers",
  "numi",
  "nvidia geforce now",
  "nvidia shadowplay",
  "nvim",
  "obs",
  "obs studio",
  "obsidian",
  "ocenaudio",
  "office",
  "office 365",
  "olive",
  "omnifocus",
  "one switch",
  "onedrive",
  "onenote",
  "onlyoffice",
  "openoffice",
  "openshot",
  "opera",
  "opera gx",
  "origami studio",
  "origin",
  "orion",
  "osu",
  "osu!",
  "outer wilds",
  "outlast",
  "outlook",
  "overcast",
  "overwatch",
  "overwatch 2",
  "ow2",
  "owncloud",
  "pages",
  "paint tool sai",
  "paint.net",
  "paintshop pro",
  "paladins",
  "palworld",
  "pandora",
  "paper mario",
  "paperpile",
  "parallels",
  "paramount plus",
  "paramount+",
  "parsec",
  "paste",
  "pastebot",
  "path finder",
  "path of exile",
  "path of exile 2",
  "paw",
  "payday",
  "payday 2",
  "payday 3",
  "paypal",
  "pcalc",
  "pcloud",
  "pcsx2",
  "pdf element",
  "pdf expert",
  "pdf pen",
  "peacock",
  "peazip",
  "penpot",
  "percy",
  "persona",
  "persona 3",
  "persona 5",
  "personal capital",
  "pgadmin",
  "phantasy star online",
  "phasmophobia",
  "philips hue",
  "photo booth",
  "photo mechanic",
  "photomath",
  "photomechanic",
  "photos",
  "photoshop",
  "phpmyadmin",
  "phpstorm",
  "pia",
  "pillars of eternity",
  "pillow",
  "pinterest",
  "pipedrive",
  "piskel",
  "pixelmator",
  "pixelmator pro",
  "planet coaster",
  "planet zoo",
  "play store",
  "playerunknowns battlegrounds",
  "playnite",
  "playstation",
  "playstation now",
  "plex",
  "plex media player",
  "plexamp",
  "pluralsight",
  "pocket",
  "pocket casts",
  "podman",
  "poe",
  "poe 2",
  "pokemon",
  "pokémon",
  "polaris office",
  "polarr",
  "portainer",
  "portal",
  "portal 2",
  "postman",
  "pot player",
  "potplayer",
  "powerpoint",
  "powershell",
  "ppsspp",
  "premiere",
  "premiere pro",
  "premiere rush",
  "presonus studio one",
  "preview",
  "prey",
  "prime video",
  "principle",
  "private internet access",
  "pro tools",
  "process monitor",
  "procreate",
  "procreate dreams",
  "project",
  "project zomboid",
  "proton vpn",
  "protonvpn",
  "prowritingaid",
  "proxyman",
  "ps now",
  "ps remote play",
  "pso2",
  "pubg",
  "publisher",
  "putty",
  "pycharm",
  "pyre",
  "pyxel edit",
  "qobuz",
  "quickbooks",
  "quicken",
  "quicksilver",
  "quicktime",
  "quicktime player",
  "quizlet",
  "r6",
  "r6s",
  "radeon software",
  "radio silence",
  "rainbow six",
  "rainbow six siege",
  "rancher",
  "rapidapi",
  "rawtherapee",
  "raycast",
  "rdr2",
  "re4",
  "readwise",
  "ready or not",
  "reaper",
  "reason",
  "recorder",
  "rectangle",
  "recuva",
  "red dead online",
  "red dead redemption",
  "red dead redemption 2",
  "reddit",
  "redis desktop",
  "redisinsight",
  "reeder",
  "reflect",
  "reminders",
  "remnant",
  "remnant 2",
  "remnant from the ashes",
  "remnote",
  "rescuetime",
  "resident evil",
  "resident evil 4",
  "resident evil village",
  "rest client",
  "retroarch",
  "returnal",
  "reuters",
  "reverso",
  "revit",
  "rhino",
  "rhinoceros",
  "rhythmbox",
  "rider",
  "rimworld",
  "ring",
  "ring central",
  "ring of elysium",
  "riot client",
  "riot games",
  "risk of rain",
  "risk of rain 2",
  "rive",
  "riverside",
  "riverside.fm",
  "roam",
  "roam research",
  "robinhood",
  "roblox",
  "robo 3t",
  "roboform",
  "rocket league",
  "rocket.chat",
  "rockstar games launcher",
  "rockstar launcher",
  "rosetta stone",
  "rpcs3",
  "rpg maker",
  "rubymine",
  "rumble",
  "runkeeper",
  "rust",
  "rx",
  "ryujinx",
  "s gate",
  "s sky",
  "safari",
  "safari technology preview",
  "sage",
  "sai",
  "salesforce",
  "samsung internet",
  "satisfactory",
  "sc2",
  "scarlet nexus",
  "screencastify",
  "screenflow",
  "screenpal",
  "screenshot",
  "screentogif",
  "scrintal",
  "scrivener",
  "sea of thieves",
  "seafile",
  "securecrt",
  "sekiro",
  "sequel ace",
  "sequel pro",
  "settings",
  "sf6",
  "shadow of the tomb raider",
  "shadowplay",
  "sharex",
  "shatterline",
  "shine",
  "shortcut",
  "shotcut",
  "sifu",
  "signal",
  "signal desktop",
  "sim city",
  "simcity",
  "simplenote",
  "sims",
  "sims 4",
  "simulator",
  "sketch",
  "sketchup",
  "ski safari",
  "skillshare",
  "skim",
  "skype",
  "skype for business",
  "skyrim",
  "slack",
  "sleep cycle",
  "sleepwatch",
  "slime rancher",
  "slobs",
  "smartgit",
  "smartsheet",
  "smash bros",
  "smite",
  "snagit",
  "snapchat",
  "snapseed",
  "snes9x",
  "sniper elite",
  "snipping tool",
  "snowrunner",
  "social club",
  "softmaker office",
  "solidworks",
  "sons of the forest",
  "sony vegas",
  "sophos",
  "soulcalibur",
  "soulver",
  "sound forge",
  "soundcloud",
  "soundtrap",
  "sourcetree",
  "space engineers",
  "spacemacs",
  "spectacle",
  "spellbreak",
  "spider-man remastered",
  "spideroak",
  "spiritfarer",
  "splatoon",
  "spline",
  "spore",
  "spotify",
  "spotify podcasts",
  "spotlight",
  "sprout social",
  "sql server management studio",
  "sqlitebrowser",
  "squad",
  "squadcast",
  "square",
  "ssms",
  "stack overflow",
  "standard notes",
  "star citizen",
  "star wars battlefront",
  "star wars jedi",
  "starcraft",
  "starcraft 2",
  "stardew valley",
  "starfield",
  "stats",
  "steam",
  "steam client",
  "steam client bootstrapper",
  "steam client webhelper",
  "steam link",
  "stellaris",
  "stitcher",
  "stopwatch",
  "storybook",
  "strava",
  "strawberry",
  "stray",
  "streaks",
  "streamelements",
  "streamlabs",
  "streamlabs obs",
  "street fighter",
  "street fighter 6",
  "stripe",
  "strongvpn",
  "studio 3t",
  "studio one",
  "sublime",
  "sublime merge",
  "sublime text",
  "subnautica",
  "substack",
  "substance",
  "substance 3d",
  "substance designer",
  "substance painter",
  "suicide squad",
  "super mario",
  "super people",
  "super smash bros",
  "superduper",
  "surfshark",
  "surviving mars",
  "swinsian",
  "switch",
  "symbolab",
  "sync",
  "syncthing",
  "system preferences",
  "tabby",
  "tableplus",
  "tailscale",
  "tales of arise",
  "tana",
  "task manager",
  "team fortress",
  "team fortress 2",
  "teams",
  "teamwork",
  "tears of the kingdom",
  "ted",
  "tekken",
  "tekken 8",
  "telegram",
  "telegram desktop",
  "ten percent happier",
  "terminal",
  "terminus",
  "terraform",
  "terraria",
  "testflight",
  "textmate",
  "tf2",
  "the binding of isaac",
  "the crew",
  "the division",
  "the elder scrolls",
  "the finals",
  "the forest",
  "the outer worlds",
  "the quarry",
  "the sims",
  "the sims 4",
  "the surge",
  "the unarchiver",
  "the walking dead",
  "the witcher",
  "the witcher 3",
  "theine",
  "thesaurus",
  "things",
  "things 3",
  "thinkorswim",
  "thorium",
  "threads",
  "thunder client",
  "ticktick",
  "tidal",
  "tiktok",
  "time doctor",
  "time machine",
  "timely",
  "timer",
  "titanfall",
  "titanfall 2",
  "to do",
  "todoist",
  "toggl",
  "toggl track",
  "tomb raider",
  "tor",
  "tor browser",
  "torchlight",
  "total commander",
  "total war",
  "total war warhammer",
  "totk",
  "tower",
  "trackmania",
  "trading view",
  "tradingview",
  "translate",
  "transmit",
  "trello",
  "trend micro",
  "tresorit",
  "tribes",
  "trilium",
  "tripadvisor",
  "tripmode",
  "tropico",
  "tumblr",
  "tunic",
  "tunnelbear",
  "tweetbot",
  "tweetdeck",
  "twinmotion",
  "twist",
  "twisted wave",
  "twitch",
  "twitch app",
  "twitch studio",
  "twitter",
  "twitterrific",
  "two point hospital",
  "uber",
  "ubereats",
  "ubisoft",
  "ubisoft connect",
  "uc browser",
  "udemy",
  "ultrakill",
  "ulysses",
  "undertale",
  "unity",
  "unity hub",
  "unravel",
  "unreal editor",
  "unreal engine",
  "uplay",
  "v rising",
  "v-ray",
  "vagrant",
  "valheim",
  "valorant",
  "vampire survivors",
  "vampyr",
  "vanilla",
  "vba",
  "vectornator",
  "veed",
  "vegas pro",
  "venmo",
  "vermintide",
  "vermintide 2",
  "viber",
  "vigor",
  "vim",
  "vimeo",
  "virtualbox",
  "visio",
  "visual studio",
  "visual studio code",
  "visualboy advance",
  "vivaldi",
  "vlc",
  "vlc media player",
  "vmix",
  "vmware",
  "vmware fusion",
  "voice memos",
  "vox",
  "vrv",
  "vs code",
  "vsco",
  "vscode",
  "vyprvpn",
  "waking up",
  "war thunder",
  "warframe",
  "warhammer",
  "warhammer 40000",
  "warhammer vermintide",
  "warp",
  "warthunder",
  "watch dogs",
  "watch dogs 2",
  "watch dogs legion",
  "waterfox",
  "wave",
  "wavelab",
  "waven",
  "waze",
  "weather",
  "weatherbug",
  "webex",
  "webstorm",
  "webull",
  "wechat",
  "weixin",
  "wezterm",
  "whatsapp",
  "whatsapp desktop",
  "whimsical",
  "wikipedia",
  "winamp",
  "window",
  "windows media player",
  "windows terminal",
  "windscribe",
  "windsurf",
  "wine",
  "winrar",
  "winzip",
  "wirecast",
  "wireshark",
  "wise",
  "witch",
  "witcher",
  "witcher 3",
  "wolfenstein",
  "wolfram",
  "wolfram alpha",
  "wondershare filmora",
  "word",
  "wordreference",
  "workflowy",
  "world clock",
  "world of tanks",
  "world of warcraft",
  "world of warships",
  "wot",
  "wow",
  "wows",
  "wps",
  "wps office",
  "wrike",
  "writeroom",
  "wwe 2k",
  "x",
  "xbox",
  "xbox app",
  "xbox console companion",
  "xbox game bar",
  "xcode",
  "xcom",
  "xcom 2",
  "xd",
  "xenia",
  "xenoblade",
  "xero",
  "xmind",
  "xsplit",
  "xsplit broadcaster",
  "yahoo finance",
  "yakuza",
  "yandex browser",
  "ynab",
  "youtube",
  "youtube music",
  "yuzu",
  "zbrush",
  "zed",
  "zelda",
  "zen browser",
  "zencastr",
  "zenless zone zero",
  "zeplin",
  "zero",
  "zerotier",
  "zoho books",
  "zoho crm",
  "zoho vault",
  "zombie army",
  "zoom",
  "zoom meeting",
  "zotero",
  "zsnes",
  "zssh",
  "zulip",
  "zzz"
]);
